name: gtm_analyst
version: "0.1.0"
config-version: 2
profile: gtm_analyst

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  gtm_analyst:
    staging:
      +materialized: view
    marts:
      +materialized: table
