SELECT
    REVENUE_ID::VARCHAR          AS REVENUE_ID,
    BOOKING_ID::VARCHAR          AS BOOKING_ID,
    ACCOUNT_ID::VARCHAR          AS ACCOUNT_ID,
    REGION::VARCHAR              AS REGION,
    OWNER_REP_ID::VARCHAR        AS OWNER_REP_ID,
    NULLIF(TRIM(SEGMENT), '')::VARCHAR AS SEGMENT,
    ACCOUNT_NAME::VARCHAR        AS ACCOUNT_NAME,
    RECOGNITION_DATE::DATE       AS RECOGNITION_DATE,
    AMOUNT::NUMBER(38,2)         AS AMOUNT
FROM {{ ref('raw_revenue') }}
