SELECT
    BOOKING_ID::VARCHAR          AS BOOKING_ID,
    ACCOUNT_ID::VARCHAR          AS ACCOUNT_ID,
    BOOKING_DATE::DATE           AS BOOKING_DATE,
    AMOUNT::NUMBER(38,2)         AS AMOUNT,
    LICENSE_TYPE::VARCHAR        AS LICENSE_TYPE,
    TERM_MONTHS::NUMBER(38,0)    AS TERM_MONTHS,
    IS_INTERCOMPANY::BOOLEAN     AS IS_INTERCOMPANY,
    CURRENCY::VARCHAR            AS CURRENCY
FROM {{ ref('raw_bookings') }}
