SELECT
    BILLING_ID::VARCHAR      AS BILLING_ID,
    BOOKING_ID::VARCHAR      AS BOOKING_ID,
    INVOICE_DATE::DATE       AS INVOICE_DATE,
    AMOUNT::NUMBER(38,2)     AS AMOUNT
FROM {{ ref('raw_billings') }}
