-- Four roles, three persona schemas.
-- Persona roles are deliberately NOT nested under one another. Nesting would let
-- a rep inherit finance visibility through the role graph, which is precisely
-- the leak the evaluation exists to catch.
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS GAA_LOADER;
CREATE ROLE IF NOT EXISTS GAA_FINANCE_GLOBAL;
CREATE ROLE IF NOT EXISTS GAA_SALES_DIR_EMEA;
CREATE ROLE IF NOT EXISTS GAA_REP_INDIVIDUAL;

GRANT ROLE GAA_LOADER         TO ROLE SYSADMIN;
GRANT ROLE GAA_FINANCE_GLOBAL TO ROLE SYSADMIN;
GRANT ROLE GAA_SALES_DIR_EMEA TO ROLE SYSADMIN;
GRANT ROLE GAA_REP_INDIVIDUAL TO ROLE SYSADMIN;

-- The operator needs to assume each persona to run the evaluation.
GRANT ROLE GAA_LOADER         TO USER GAA_OPERATOR;
GRANT ROLE GAA_FINANCE_GLOBAL TO USER GAA_OPERATOR;
GRANT ROLE GAA_SALES_DIR_EMEA TO USER GAA_OPERATOR;
GRANT ROLE GAA_REP_INDIVIDUAL TO USER GAA_OPERATOR;

USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS GAA;
CREATE SCHEMA IF NOT EXISTS GAA.MARTS;
CREATE SCHEMA IF NOT EXISTS GAA.FINANCE;
CREATE SCHEMA IF NOT EXISTS GAA.EMEA;
CREATE SCHEMA IF NOT EXISTS GAA.REP;
