-- Identical view NAMES in three schemas, different definitions. This IS the
-- boundary: an unqualified query resolves against the session's default schema,
-- so one SQL string returns three different correct answers.
-- CREATE OR REPLACE because dbt drops dependents whenever it rebuilds a mart.
USE ROLE SYSADMIN;

-- ---------------------------------------------------------------- FINANCE
-- Everything, account names in the clear.
CREATE OR REPLACE SECURE VIEW GAA.FINANCE.V_BOOKINGS  AS SELECT * FROM GAA.MARTS.FCT_BOOKINGS;
CREATE OR REPLACE SECURE VIEW GAA.FINANCE.V_BILLINGS  AS SELECT * FROM GAA.MARTS.FCT_BILLINGS;
CREATE OR REPLACE SECURE VIEW GAA.FINANCE.V_REVENUE   AS SELECT * FROM GAA.MARTS.FCT_REVENUE;
CREATE OR REPLACE SECURE VIEW GAA.FINANCE.V_ACCOUNT   AS SELECT * FROM GAA.MARTS.DIM_ACCOUNT;
CREATE OR REPLACE SECURE VIEW GAA.FINANCE.V_TERRITORY AS SELECT * FROM GAA.MARTS.DIM_TERRITORY_SCD;

-- ---------------------------------------------------------------- EMEA
-- Region-filtered, account names masked. Masking changes distinct values but
-- never row counts, which is what the masking_preserves_row_count invariant
-- asserts.
CREATE OR REPLACE SECURE VIEW GAA.EMEA.V_BOOKINGS AS
    SELECT * FROM GAA.MARTS.FCT_BOOKINGS WHERE REGION = 'EMEA';
CREATE OR REPLACE SECURE VIEW GAA.EMEA.V_BILLINGS AS
    SELECT * FROM GAA.MARTS.FCT_BILLINGS WHERE REGION = 'EMEA';
CREATE OR REPLACE SECURE VIEW GAA.EMEA.V_REVENUE AS
    SELECT * FROM GAA.MARTS.FCT_REVENUE WHERE REGION = 'EMEA';
CREATE OR REPLACE SECURE VIEW GAA.EMEA.V_ACCOUNT AS
    SELECT ACCOUNT_ID,
           'ACCOUNT-' || RIGHT(SHA2(ACCOUNT_NAME), 8) AS ACCOUNT_NAME,
           REGION, SEGMENT, OWNER_REP_ID
    FROM GAA.MARTS.DIM_ACCOUNT WHERE REGION = 'EMEA';
CREATE OR REPLACE SECURE VIEW GAA.EMEA.V_TERRITORY AS
    SELECT * FROM GAA.MARTS.DIM_TERRITORY_SCD WHERE REGION = 'EMEA';

-- ---------------------------------------------------------------- REP
-- Own accounts only, names masked.
-- REP001 is hardcoded. A real deployment maps CURRENT_USER() to a rep; the
-- hardcode is acceptable for a single-operator reference deployment and is
-- listed as accepted risk in the threat model rather than left implicit.
CREATE OR REPLACE SECURE VIEW GAA.REP.V_BOOKINGS AS
    SELECT * FROM GAA.MARTS.FCT_BOOKINGS WHERE OWNER_REP_ID = 'REP001';
CREATE OR REPLACE SECURE VIEW GAA.REP.V_BILLINGS AS
    SELECT * FROM GAA.MARTS.FCT_BILLINGS WHERE OWNER_REP_ID = 'REP001';
CREATE OR REPLACE SECURE VIEW GAA.REP.V_REVENUE AS
    SELECT * FROM GAA.MARTS.FCT_REVENUE WHERE OWNER_REP_ID = 'REP001';
CREATE OR REPLACE SECURE VIEW GAA.REP.V_ACCOUNT AS
    SELECT ACCOUNT_ID,
           'ACCOUNT-' || RIGHT(SHA2(ACCOUNT_NAME), 8) AS ACCOUNT_NAME,
           REGION, SEGMENT, OWNER_REP_ID
    FROM GAA.MARTS.DIM_ACCOUNT WHERE OWNER_REP_ID = 'REP001';
CREATE OR REPLACE SECURE VIEW GAA.REP.V_TERRITORY AS
    SELECT * FROM GAA.MARTS.DIM_TERRITORY_SCD WHERE REP_ID = 'REP001';

GRANT SELECT ON ALL VIEWS IN SCHEMA GAA.FINANCE TO ROLE GAA_FINANCE_GLOBAL;
GRANT SELECT ON ALL VIEWS IN SCHEMA GAA.EMEA    TO ROLE GAA_SALES_DIR_EMEA;
GRANT SELECT ON ALL VIEWS IN SCHEMA GAA.REP     TO ROLE GAA_REP_INDIVIDUAL;
